version: "3.8"
services:

  postgis:
    image: "mdillon/postgis"
    hostname: postgis
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgresql_data_volume
        target: /var/lib/postgresql/data
      
  geoserver:
    image: "kartoza/geoserver"
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: geoserver_data_volume
        target: /opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - HTTP_PROXY_NAME=${CODESPACE_NAME}-8080.app.github.dev
      - HTTP_PROXY_PORT=443
      - HTTP_SCHEME=https
      - MAXIMUM_MEMORY=756M
      - INITIAL_MEMORY=128M
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  postgresql_data_volume:
  geoserver_data_volume:
  
networks:
  default:
    name: gist604b
