version: "3.8"
services:

  postgis:
    image: "mdillon/postgis"
    hostname: postgis
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgresql_data_volume
        target: /var/lib/postgresql/data
      
  geoserver:
    image: docker.osgeo.org/geoserver:2.24.x
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: geoserver_data_volume 
        # target: /opt/geoserver/data_dir
        target: /opt/geoserver_data
      # - type: bind
      #   source: ./settings/web.xml
      #   target: /usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    environment:
      - ROOT_WEBAPP_REDIRECT=true
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=${CODESPACE_NAME}-8080.app.github.dev
      - CORS_ALLOW_CREDENTIALS=true
      - PROXY_BASE_URL=https://${CODESPACE_NAME}-8080.app.github.dev/geoserver
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 1G

volumes:
  postgresql_data_volume:
  geoserver_data_volume:
  
networks:
  default:
    name: gist604b
